### PR TITLE
Bump version to 0.9.9

### PR DESCRIPTION
**Pull request by joe-keane**
@tomasmcguinness do you mind to build a new nupkg after merging this?

### CODE REVIEW

**Comment by tuler** [comment]
I also need a 0.9.9, but please check #45 first.
It's the only issue we have in our application currently.

**Comment by joe-keane** [comment]
I'll take a look into it.
BTW seems like I didn't revert the format for "expirationDate".

**Comment by joe-keane** [comment]
Set both relevantDate and expirationDate with K instead of zzz.
Based on a low amount of tests it's working as expected
Pending some tests using a device.

**Comment by tuler** [comment]
Any conclusion? Can we have a 0.9.9 with K format?

**Comment by tuler** [comment]
Can we have a 0.9.9 at nuget?
Thanks!

**Comment by tomasmcguinness** [comment]
Sure, I'm just back from my holidays, so sorry for the delay.

**Comment by tuler** [comment]
Any progress?

**Pull request merged**
