### PR TITLE
Refactored dotnet-passbook

### PR DESCRIPTION
**Pull request by the-darkvoid**
Hi,

I have done some refactoring of the dotnet-pass book library code, resolving some small issues.

Most importantly making it compile on Xamarin Mono on OS X and removing the BounceCastle dependency in favour of standard .NET framework generation of the signature.

Also the footer image when included was not represented in the manifest.json hash blob.

Additionally added the new iOS 7 ignoresTimeZone property and resolved an issue with dataDetectorTypes not rendering in the output JSON.

### CODE REVIEW

**Comment by tuler** [comment]
Seems like a very nice refactoring. The template feature is very usefull.
Any chance of accepting this @tomasmcguinness ?

**Comment by tomasmcguinness** [comment]
I'm planning to, but I just haven't had the time to read through it. Should get it done this Saturday.

**Comment by tomasmcguinness** [comment]
I'll get a new Nuget package ready with this over the weekend.

**Comment by tuler** [comment]
Great! Thanks!

**Comment by ChristianBecker** [comment]
@tomasmcguinness Hey, can you release a 0.9.8 release with this changes? AFAIK the most recent version in NuGet is still the 0.9.7 one which depends on BouncyCastle…

**Comment by tuler** [comment]
We also need a 0.9.8!
We're also opening a new PR today, which we wanted to include in 0.9.8.

If you are not maintaining it, can you give permission to someone else to publish it to NuGet?

**Comment by tomasmcguinness** [comment]
All,
I've just compiled from Master and pushed 0.9.8 to Nuget. Please let me know if anything appears amiss.

**Pull request merged**
