### PR TITLE
Add optional major and minor property to Beacon #26

### PR DESCRIPTION
**Pull request by KevM**
Saw Issue #26 and thought it looked like an easy place to help out. I followed the Passbook spec for [Beacon Dictionary Keys](https://developer.apple.com/library/ios/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/LowerLevel.html#//apple_ref/doc/uid/TP40012026-CH3-SW4)

CAVET: I do not have any iBeacons to test this

### CODE REVIEW

**Comment by KevM** [comment]
Noticed that `AddBeacon` was responsible for creating Beacons and needed the major, minor arguments. I made them optional to avoid breaking compatibility and since they really are optional.

**Comment by tuler** [comment]
+1

**Comment by tomasmcguinness** [comment]
I added these code changes a few months back but never closed the pull request. Sorry!

**Comment by tuler** [comment]
I don't see it in the master branch.

**Comment by tomasmcguinness** [comment]
Apologies! It's there now.

**Comment by tuler** [comment]
Great, thanks! Do you have plans to release a 0.9.8 to nuget?

**Comment by KevM** [comment]
Glad the change went in. Sad my commit seems to have been arbitrarily not used.

**Comment by tomasmcguinness** [comment]
Kevin,

Sorry! I had no clue what to do with the pull request when you first raised it so I just copied the code.

I appreciate the input and now that I've figured out how to merge them, I'll do it right in future.

Tom

**Comment by tuler** [comment]
Can we help to have a 0.9.8 out?

**Pull request closed without merging**
